import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Layout.jsx
import React from 'react';
import { Leaf, Home, Settings, User, LogOut } from 'lucide-react';
const Layout = ({ children, onLogout, onViewChange, currentView }) => {
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("nav", { className: "bg-white shadow-md", children: _jsx("div", { className: "max-w-7xl mx-auto px-4", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Leaf, { className: "h-8 w-8 text-green-600" }), _jsx("span", { className: "ml-2 text-xl font-bold text-gray-800", children: "Kalamkar Exotics" })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx(NavLink, { icon: _jsx(Home, { size: 25 }), text: "Dashboard", active: currentView === 'orders', onClick: () => onViewChange('orders') }), _jsx(NavLink, { icon: _jsx(Leaf, { size: 25 }), text: "Orders", active: currentView === 'orders', onClick: () => onViewChange('orders') }), _jsx(NavLink, { icon: _jsx(Settings, { size: 25 }), text: "Settings", active: currentView === 'settings', onClick: () => onViewChange('settings') }), _jsx(NavLink, { icon: _jsx(User, { size: 25 }), text: "Profile", active: currentView === 'profile', onClick: () => onViewChange('profile') }), _jsxs("button", { onClick: onLogout, className: "flex items-center px-3 py-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors", children: [_jsx(LogOut, { size: 25, className: "mr-2" }), "Logout"] })] })] }) }) }), _jsx("main", { className: "max-w-7xl mx-auto px-4 py-8", children: _jsx("div", { className: "flex flex-col items-center", children: children }) }), _jsx("footer", { className: "bg-white border-t mt-auto", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 py-6", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center", children: [_jsx(Leaf, { className: "h-6 w-6 text-green-600 mr-2" }), _jsx("span", { className: "text-gray-600", children: "Kalamkar Exotics Pvt Ltd" })] }), _jsx("div", { className: "text-gray-500 text-sm", children: "\u00A9 2024 Kalamkar Exotics Pvt Ltd. All rights reserved." })] }) }) })] }));
};
const NavLink = ({ icon, text, active, onClick }) => (_jsxs("button", { onClick: onClick, className: `flex items-center px-3 py-2 rounded-lg transition-colors
      ${active
        ? 'bg-green-50 text-green-600'
        : 'text-gray-600 hover:bg-gray-50'}`, children: [icon, _jsx("span", { className: "ml-2", children: text })] }));
export default Layout;
